name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install necessary dependencies
    - name: Install dependencies
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.gz
        tar -xzf boost_1_83_0.tar.gz
        cd boost_1_83_0
        ./bootstrap.sh --prefix=/usr/local
        ./b2
        sudo ./b2 install
        sudo apt-get update && sudo apt-get install -y cmake libcurl4-openssl-dev

    # Configure and build the project
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j4

    # Optional: Add steps for any tests or additional checks
    # - name: Run tests
    #   run: |
    #     cd build
    #     make test

    # Optional: Run the executable if needed
    # - name: Run CommanderChris
    #   run: |
    #     cd build
    #     ./Chris
