name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup code to compile with g++17
    - name: Setup g++17
      uses: actions/setup-gcc@v1
      with:
        gcc-version: 17

    # Install necessary dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y cmake libcurl4-openssl-dev
      
    # Configure and build the project
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j4

    # Optional: Add steps for any tests or additional checks
    # - name: Run tests
    #   run: |
    #     cd build
    #     make test

    # Optional: Run the executable if needed
    # - name: Run CommanderChris
    #   run: |
    #     cd build
    #     ./Chris
