name: CMake on multiple platforms

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on tag push matching v*, e.g., v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]  # Removed windows-latest
        build_type: [Release]
        c_compiler: [gcc, clang]  # Removed cl as it's specific to Windows
        include:
          # Commented out the Windows specific build
          # - os: windows-latest
          #   c_compiler: cl
          #   cpp_compiler: cl
          #   artifact_name: chris-windows
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            artifact_name: chris-linux
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            artifact_name: chris-linux-clang
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            artifact_name: chris-macos
        exclude:
          # Commented out the Windows specific exclusions
          # - os: windows-latest
          #   c_compiler: gcc
          # - os: windows-latest
          #   c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3

    # Archive the source code
    - name: Archive source code
      run: |
        tar -czf source-code.tar.gz --exclude=.git .

    # Upload the source code archive as an artifact
    - name: Upload source code artifact
      uses: actions/upload-artifact@v2
      with:
        name: source-code-${{ matrix.os }}
        path: source-code.tar.gz

    # Install necessary dependencies for Ubuntu
    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y cmake libcurl4-openssl-dev libboost-all-dev

    # Install necessary dependencies for macOS
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install cmake boost curl

    # Commented out the Windows dependency installation step
    # - name: Install dependencies (Windows)
    #   if: runner.os == 'Windows'
    #   run: |
    #     choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
    #     choco install curl
    #     choco install boost-msvc-14.3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ steps.strings.outputs.build-output-dir }}/chris

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Download all artifacts (binaries and source code archive)
    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    # Create GitHub Release and attach artifacts
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
